### ISSUE TITLE
ApolloQuery inheritance chain [design]

### ISSUE THREAD

**Issue by padzikm** [apollo-elements/apollo-elements#38]
I'd like to notice that:
```javascript
ApolloQuery extends ApolloQueryMixin(ApolloElement)

ApolloElement extends ApolloElementMixin(LitElement)

ApolloQueryMixin = superclass => class extends ApolloElementMixin(superclass)

ApolloElementMixin = superclass => class extends superclass
```
as a result ApolloElementMixin is applied to both LitElement and then to ApolloElement (which extends LitElement) - is this on purpose?

**Comment by bennypowers** [comment]
:wave: Hi @padzikm thanks for the issue.

As you'll notice, `ApolloElementMixin` provides the mutation observer, while `ApolloElement` base class provides some LitElement observed properties. The upshot of this is that we get, as you pointed out, a double application of `ApolloElementMixin` on `ApolloQuery`.

I don't think this is a huge issue, since the mixin will just override the existing (identical) properties on the resulting object, however you could argue that those are wasted cycles, and you'd be right.

This way, however, provides maximum flexibility for users who want to (for whatever reason) extend from `ApolloElement`.

Do you have another solution in mind?

**Comment by bennypowers** [comment]
This will be solved with the adoption of `dedupeMixin` in an upcoming version
